# Auto-generated by CMake - DO NOT EDIT
# Makefile wrapper for developers (uses CMake underneath)
# Users: Use build.sh instead (no CMake required)

.PHONY: all build benchmark test test-c test-lua lint format clean help bump-patch bump-minor bump-major bump-prerelease

all: build

build:
	@cmake -B build -S .
	@cmake --build build
	@echo "✓ Build successful"

benchmark:
	@./scripts/benchmark.sh

test: test-c test-lua

test-c: build
	@cd build && ctest --output-on-failure

test-lua:
	@./tests/run_plenary_tests.sh

lint:
	@stylua --check lua

format:
	@stylua lua
	@echo "✓ Formatted lua/"

clean:
	@rm -rf build
	@rm -f libvscode_diff.so libvscode_diff.dylib

bump-patch:
	@node scripts/bump_version.mjs patch

bump-minor:
	@node scripts/bump_version.mjs minor

bump-major:
	@node scripts/bump_version.mjs major

bump-prerelease:
	@node scripts/bump_version.mjs prerelease

help:
	@echo "Targets: build, benchmark, test, test-c, test-lua, lint, clean, help"
	@echo "Version: bump-patch, bump-minor, bump-major, bump-prerelease"
