@echo off
REM Auto-generated by CMake - DO NOT EDIT MANUALLY
REM This script allows building without CMake installed
REM Auto-detects compiler: MSVC, Clang, MinGW GCC

setlocal enabledelayedexpansion
cd /d "%~dp0\libvscode-diff"
set "OUTPUT_PATH=%~1"
if not defined OUTPUT_PATH set "OUTPUT_PATH=..\libvscode_diff.dll"
set "BUILD_DIR=%~2"
if not defined BUILD_DIR set "BUILD_DIR=build"

REM Create build directory
if not exist "!BUILD_DIR!" mkdir "!BUILD_DIR!"
if not exist "!BUILD_DIR!\include" mkdir "!BUILD_DIR!\include"

REM Generate version.h from VERSION file
set /p VERSION=<..\VERSION
powershell -NoLogo -NoProfile -Command "(Get-Content include\version.h.in) -replace ('@' + 'PROJECT_VERSION' + '@'), '!VERSION!' | Set-Content '!BUILD_DIR!\include\version.h'"

echo Building vscode_diff (standalone mode)...
echo Platform: Windows
echo Version: !VERSION!

REM Source files (including bundled utf8proc)
set SOURCES=^
default_lines_diff_computer.c ^
src\char_level.c ^
src\line_level.c ^
src\line_matcher.c ^
src\myers.c ^
src\optimize.c ^
src\sequence.c ^
src\range_mapping.c ^
src\string_hash_map.c ^
src\utils.c ^
src\print_utils.c ^
src\utf8_utils.c ^
src\compute_moved_lines.c ^
vendor\utf8proc.c

REM Auto-detect compiler
set COMPILER=unknown

where cl.exe >nul 2>&1
if !errorlevel! == 0 (
    set COMPILER=msvc
    goto :build_msvc
)

where clang.exe >nul 2>&1
if !errorlevel! == 0 (
    set COMPILER=clang
    goto :build_clang
)

where gcc.exe >nul 2>&1
if !errorlevel! == 0 (
    set COMPILER=gcc
    goto :build_gcc
)

echo Error: No C compiler found!
echo Please install one of: Visual Studio (MSVC), Clang, MinGW-w64
cd ..
exit /b 1

:build_msvc
echo Using MSVC compiler...
REM Check for OpenMP support (MSVC has built-in support)
set OMP_FLAGS=
set OMP_LINK=
cl.exe /? 2>&1 | findstr /C:"/openmp" >nul
if !errorlevel! == 0 (
    echo OpenMP: enabled
    set OMP_FLAGS=/openmp /DUSE_OPENMP
) else (
    echo OpenMP: disabled
)
cl.exe /LD /O2 /W3 /std:c11 /DUTF8PROC_STATIC /DBUILDING_DLL !OMP_FLAGS! /Iinclude /I"!BUILD_DIR!\include" /Ivendor /Fo"!BUILD_DIR!\" /Fd"!BUILD_DIR!\" /Fe:"!OUTPUT_PATH!" %SOURCES% /link /DLL /DEF:libvscode_diff.def
goto :build_done

:build_clang
echo Using Clang compiler...
if not exist build mkdir build
REM Check for OpenMP support with Clang
set OMP_FLAGS=
echo int main() { return 0; } > %TEMP%\omp_test.c
clang.exe -fopenmp %TEMP%\omp_test.c -o %TEMP%\omp_test.exe 2>nul
if !errorlevel! == 0 (
    echo OpenMP: enabled
    set OMP_FLAGS=-fopenmp -DUSE_OPENMP
) else (
    echo OpenMP: disabled
)
del /q %TEMP%\omp_test.c %TEMP%\omp_test.exe 2>nul
clang.exe -shared -Wall -Wextra -std=c11 -O2 -DUTF8PROC_STATIC !OMP_FLAGS! -Iinclude -I"!BUILD_DIR!\include" -Ivendor -o "!OUTPUT_PATH!" %SOURCES%
goto :build_done

:build_gcc
echo Using MinGW GCC compiler...
if not exist build mkdir build
REM Check for OpenMP support with GCC
set OMP_FLAGS=
echo int main() { return 0; } > %TEMP%\omp_test.c
gcc.exe -fopenmp %TEMP%\omp_test.c -o %TEMP%\omp_test.exe 2>nul
if !errorlevel! == 0 (
    echo OpenMP: enabled
    set OMP_FLAGS=-fopenmp -DUSE_OPENMP
) else (
    echo OpenMP: disabled
)
del /q %TEMP%\omp_test.c %TEMP%\omp_test.exe 2>nul
gcc.exe -shared -Wall -Wextra -std=c11 -O2 -DUTF8PROC_STATIC !OMP_FLAGS! -Iinclude -I"!BUILD_DIR!\include" -Ivendor -o "!OUTPUT_PATH!" %SOURCES%
goto :build_done

:build_done
if !errorlevel! neq 0 (
    echo Build failed!
    cd ..
    exit /b 1
)

echo.
echo [OK] Build successful: !OUTPUT_PATH!
cd ..
endlocal
